"""A real walk across 3k.org, extracted from a session capture.

Player walked from the Center of Town out through the newbie area, the
residential district, science, chaos, back through town and on to the fantasy
entrance.  Events are in the order the client saw them: ``sent`` when a command
went out, ``room`` when a room block opened, each with the timestamp it
actually carried.  The overlaps are the point -- there are moments with two
commands outstanding, a move that failed silently, and blocks that no command
caused.

Kept as data rather than a capture file because captures are gitignored: they
are large, personal, and irreplaceable.
"""

WALK = [
    ("sent", 168.17, 's'),
    ("sent", 169.75, 'w'),
    ("room", 168.32, ['e', 'n', 's', 'w'], ['building', 'center', 'tankard']),
    ("sent", 170.95, 's'),
    ("room", 170.41, ['e', 's', 'w'], ['bulk', 'forest', 'sky', 'track', 'trail']),
    ("sent", 171.35, 's'),
    ("room", 171.02, ['n', 's', 'w'], ['border', 'building', 'clearing']),
    ("sent", 172.05, 'e'),
    ("room", 171.42, ['d', 'e', 'n', 's', 'w'], ['lights', 'sky', 'whirl']),
    ("sent", 172.69, 's'),
    ("room", 172.31, ['w'], ['altar', 'pews', 'row', 'windows']),
    ("sent", 175.01, 'w'),
    ("sent", 175.5, 's'),
    ("room", 175.08, ['d', 'e', 'n', 's', 'w'], ['lights', 'sky', 'whirl']),
    ("sent", 175.99, 'e'),
    ("room", 175.57, ['e', 'n', 'w'], ['clearing', 'forest']),
    ("sent", 176.52, 's'),
    ("room", 176.36, ['e', 's', 'w'], ['church', 'spires']),
    ("room", 176.59, ['e', 'n', 's', 'sw', 'w'], ['gate', 'lane', 'pasture', 'path', 'restaurant']),
    ("sent", 183.82, 'n'),
    ("sent", 184.99, 'e'),
    ("room", 184.26, ['e', 's', 'w'], ['church', 'spires']),
    ("sent", 185.44, 'e'),
    ("room", 185.03, ['e', 'w'], ['building', 'shop']),
    ("room", 185.5, ['e', 'n', 's', 'se', 'w'], ['archway', 'fields', 'intersection', 'street', 'vista']),
    ("sent", 186.61, 's'),
    ("sent", 187.29, 'n'),
    ("room", 186.67, ['n'], ['home', 'homes']),
    ("sent", 187.74, 'n'),
    ("room", 187.35, ['e', 'n', 's', 'se', 'w'], ['archway', 'fields', 'intersection', 'street', 'vista']),
    ("sent", 188.8, 'n'),
    ("room", 188.41, ['e', 'n', 's', 'w'], ['shop', 'soot', 'street', 'structure', 'walls']),
    ("sent", 190.14, 'n'),
    ("room", 188.86, ['e', 'n', 's'], ['soot', 'street', 'walls']),
    ("sent", 191.87, 'n'),
    ("room", 190.39, ['e', 'n', 's', 'w'], ['intersection', 'street']),
    ("sent", 192.86, 'e'),
    ("room", 192.34, ['e', 'n', 's'], ['building', 'road']),
    ("sent", 193.31, 'e'),
    ("room", 192.9, ['e', 'ne', 'w'], ['city', 'road', 'ruin', 'sign']),
    ("sent", 194.23, 'w'),
    ("room", 193.35, ['e', 'enter', 's', 'se', 'w'], ['city', 'gateway', 'ground', 'road']),
    ("sent", 194.58, 'w'),
    ("room", 194.31, ['e', 'ne', 'w'], ['city', 'road', 'ruin', 'sign']),
    ("sent", 195.15, 'n'),
    ("room", 194.64, ['e', 'n', 's'], ['building', 'road']),
    ("sent", 195.52, 'n'),
    ("room", 195.22, ['e', 'n', 's', 'w'], ['shed', 'sky']),
    ("sent", 196.04, 'n'),
    ("room", 195.59, ['e', 'n', 's'], ['building', 'field', 'fields', 'hut', 'sky']),
    ("sent", 196.76, 'w'),
    ("room", 196.39, ['e', 's', 'w'], ['air', 'building', 'clouds', 'haze', 'lightning', 'manhole', 'path']),
    ("sent", 197.13, 'w'),
    ("room", 196.8, ['e', 'w'], ['haze']),
    ("sent", 197.73, 'n'),
    ("room", 197.17, ['e', 'n', 'w'], ['bricks', 'haze', 'stones']),
    ("room", 198.29, ['e', 'enter', 's', 'w'], ['flashes', 'mass', 'road', 'sky', 'vortex']),
    ("sent", 232.13, 's'),
    ("sent", 232.54, 'w'),
    ("room", 232.41, ['e', 'n', 'w'], ['bricks', 'haze', 'stones']),
    ("sent", 233.15, 's'),
    ("room", 232.6, ['e', 'n', 'nw', 's', 'w'], ['building', 'clouds', 'shop', 'sky']),
    ("sent", 233.46, 's'),
    ("room", 233.19, ['n', 's', 'w'], ['edifice', 'side']),
    ("room", 233.53, ['e', 'n', 'w'], ['rain', 'sky', 'tiles']),
    ("sent", 234.88, 'e'),
    ("sent", 235.23, 's'),
    ("room", 234.95, ['e', 'n', 's', 'w'], ['building', 'tile']),
    ("room", 235.27, ['d', 'e', 'jump', 'n', 'omp', 's', 'w'], ['base', 'building', 'edifice', 'lights', 'shadows', 'sky', 'street', 'structure']),
    ("sent", 237.29, 's'),
    ("sent", 237.57, 'w'),
    ("room", 237.36, ['e', 'n', 's', 'w'], ['building', 'center', 'tankard']),
    ("sent", 237.8, 'w'),
    ("sent", 238.13, 'n'),
    ("room", 237.63, ['e', 's', 'w'], ['bulk', 'forest', 'sky', 'track', 'trail']),
    ("room", 238.35, ['e', 'n'], ['building']),
    ("sent", 238.77, 'w'),
    ("room", 238.37, ['n', 's', 'w'], ['bulk', 'path', 'sky']),
    ("sent", 239.0, 'w'),
    ("room", 238.81, ['e', 'n', 's', 'w'], ['hut', 'path', 'trees']),
    ("sent", 239.23, 'w'),
    ("room", 239.06, ['e', 'n', 's', 'w'], ['forest', 'intersection', 'path', 'road', 'trees']),
    ("room", 239.27, ['e', 'portal', 'w'], []),
    ("sent", 470.07, 'spamwho'),
    ("sent", 472.46, 'spam moo'),
    ("sent", 763.19, 'spam whats pimpin?'),
    ("sent", 1658.3, 'l'),
    ("room", 1658.65, ['e', 'portal', 'w'], ['color', 'portal', 'road', 'tower']),
    ("sent", 1799.09, 'hug marlon'),]
