"""3kdb's crafting tables: gem recipes and jewels.

From modules/crafting/data.tin and modules/professions/data.tin.  3kdb is
public domain (the Unlicense).  Read by the Crafting helpers pack.
"""

#: (gem, first level, last level, jewels, fragment, effect)
GEMS = (
    ('Minor Might', 1, 5, ('Aquamarine', 'Aquamarine Dust'), 'Fragment of Light', 'Str'),
    ('Minor Blades Aggression', 1, 5, ('Copper Shards', "Tiger's Eye"), 'Fragment of Light', 'Edged WC'),
    ('Minor Blades Protection', 2, 6, ('Copper Shards', 'Morganite'), 'Fragment of Light', 'Edged AC'),
    ('Minor Crushing Protection', 3, 7, ('Aquamarine', "Tiger's Eye Dust"), 'Fragment of Water', 'Blunt AC'),
    ('Minor Agility', 3, 7, ('Copper Shards', "Tiger's Eye"), 'Fragment of Light', 'Dex'),
    ('Minor Crushing Aggression', 4, 8, ('Aquamarine', "Tiger's Eye Dust"), 'Fragment of Water', 'Blunt WC'),
    ('Minor Flame Protection', 5, 9, ('Eye of Flame', 'Morganite Dust'), 'Fragment of Light', 'Fire AC'),
    ('Minor Flame Aggression', 6, 10, ('Eye of Flame', 'Morganite Dust'), 'Fragment of Light', 'Fire WC'),
    ('Minor Endurance', 7, 11, ('Morganite', "Tiger's Eye Dust"), 'Fragment of Shadow', 'Con'),
    ('Minor Frost Protection', 8, 12, ('Eye of Frost', 'Morganite Dust'), 'Fragment of Water', 'Ice AC'),
    ('Minor Frost Aggression', 9, 13, ('Eye of Frost', 'Morganite Dust'), 'Fragment of Water', 'Ice WC'),
    ('Minor Acid Protection', 10, 14, ('Bronze Shards', 'Morganite'), 'Fragment of Might', 'Acid AC'),
    ('Minor Lion', 10, 14, ("Cat's Eye", 'Iron Shards'), 'Fragment of Might', 'Str/Con'),
    ('Minor Acid Aggression', 11, 15, ('Bronze Shards', 'Morganite'), 'Fragment of Might', 'Acid WC'),
    ('Minor Terminator', 11, 15, ("Cat's Eye Dust", 'Eye of Flame'), 'Fragment of Might', 'Str/Dex'),
    ('Minor Electric Protection', 12, 16, ('Bronze Shards', "Cat's Eye"), 'Fragment of Rage', 'Electric AC'),
    ('Minor Smarts', 12, 16, ("Cat's Eye", 'Iron Shards'), 'Fragment of Shadow', 'Int'),
    ('Minor Clever Thief', 13, 17, ('Eye of Flame', 'Iron Shards'), 'Fragment of Shadow', 'Dex/Int'),
    ('Minor Electric Aggression', 13, 17, ('Bronze Shards', "Cat's Eye"), 'Fragment of Rage', 'Electric WC'),
    ('Minor Wolf', 15, 19, ('Eye of Flame', 'Garnet Dust'), 'Fragment of Soul', 'Dex/Con'),
    ('Minor Mental Protection', 15, 19, ('Alexandrite', 'Steel Shards'), 'Fragment of Rage', 'Mind AC'),
    ('Minor Scholar', 15, 19, ("Cat's Eye Dust", 'Garnet'), 'Fragment of Soul', 'Int/Wis'),
    ('Minor Suave Thief', 16, 20, ('Eye of Frost', 'Garnet Dust'), 'Fragment of Soul', 'Dex/Cha'),
    ('Minor Insight', 16, 20, ('Garnet', 'Garnet Dust'), 'Fragment of Soul', 'Wis'),
    ('Minor Mental Aggression', 16, 20, ('Alexandrite', 'Steel Shards'), 'Fragment of Rage', 'Mind WC'),
    ('Minor Energy Protection', 17, 21, ('Garnet', 'Steel Shards'), 'Fragment of Soul', 'Energy AC'),
    ('Minor Energy Aggression', 18, 22, ('Garnet', 'Steel Shards'), 'Fragment of Soul', 'Energy WC'),
    ('Minor Assault Protection', 18, 22, ('Alexandrite', 'Silver Shards'), 'Fragment of The Unseen', 'Edged and Blunt AC'),
    ('Minor Persuasiveness', 18, 22, ('Alexandrite Dust', 'Garnet'), 'Fragment of The Unseen', 'Cha'),
    ('Minor Barbarian', 19, 23, ('Alexandrite', 'Alexandrite Dust'), 'Fragment of The Unseen', 'Int/Str'),
    ('Minor Assault Aggression', 19, 23, ('Eye of Earth', 'Silver Shards'), 'Fragment of The Unseen', 'Edged and Blunt WC'),
    ('Minor Elements Protection', 20, 24, ('Eye of Flame', 'Eye of Frost'), 'Fragment of The Unseen', 'Fire and Ice AC'),
    ('Minor Jackal', 20, 24, ('Alexandrite', 'Alexandrite Dust'), 'Fragment of Ascension', 'Int/Con'),
    ('Minor Elements Aggression', 21, 25, ('Eye of Flame', 'Eye of Frost'), 'Fragment of The Unseen', 'Fire and Ice WC'),
    ('Minor Poison Protection', 21, 25, ("Roan's Tears", 'Silver Shards'), 'Fragment of Ascension', 'Poison AC'),
    ('Minor Thespian', 21, 25, ('Beryl', 'Garnet Dust'), 'Fragment of Ascension', 'Int/Cha'),
    ('Minor Poison Aggression', 22, 26, ("Roan's Tears", 'Silver Shards'), 'Fragment of Ascension', 'Poison WC'),
    ('Minor Detective', 22, 26, ('Eye of Earth', 'Pyrite Dust'), 'Fragment of Blasting', 'Str/Cha'),
    ('Minor Thief At Large', 23, 27, ('Pyrite', 'Pyrite Dust'), 'Fragment of Blasting', 'Dex/Wis'),
    ('Minor Radiation Protection', 23, 27, ('Pyrite', 'Silver Shards'), 'Fragment of Damnation', 'Radiation AC'),
    ('Minor Devouring Protection', 24, 28, ('Eye of Earth', 'Silver Shards'), 'Fragment of Willy', 'Poison and Acid AC'),
    ('Minor Radiation Aggression', 24, 28, ('Pyrite', 'Silver Shards'), 'Fragment of Damnation', 'Radiation WC'),
    ('Minor Elephant', 25, 29, ('Pyrite Dust', "Roan's Tears"), 'Fragment of Willy', 'Con/Wis'),
    ('Minor Devouring Aggression', 26, 30, ('Beryl', 'Silver Shards'), 'Fragment of Willy', 'Poison and Acid WC'),
    ('Minor Abbot', 27, 31, ('Pyrite', 'Tourmaline Dust'), 'Fragment of Destruction', 'Wis/Cha'),
    ('Minor Domination Protection', 27, 31, ("Roan's Tears", 'Silver Shards'), 'Fragment of Destruction', 'Mind and Energy AC'),
    ('Minor Agent', 28, 32, ('Beryl Dust', 'Tourmaline'), 'Fragment of Compassion', 'Str/Wis'),
    ('Minor Athlete', 28, 32, ('Beryl', 'Tourmaline Dust'), 'Fragment of Knowledge', 'Str/Dex/Con'),
    ('Minor Irradiation Aggression', 29, 33, ('Gold Shards', 'Tourmaline'), 'Fragment of Compassion', 'Electric and Radiation WC'),
    ('Minor Domination Aggression', 29, 33, ("Roan's Tears", 'Silver Shards'), 'Fragment of Destruction', 'Mind and Energy WC'),
    ('Minor Irradiation Protection', 30, 34, ('Gold Shards', 'Tourmaline'), 'Fragment of Compassion', 'Electric and Radiation AC'),
    ('Minor Koala', 30, 34, ('Eye of Air', 'Tourmaline Dust'), 'Fragment of Knowledge', 'Con/Cha'),
    ('Minor Despot', 31, 35, ('Amethyst Dust', 'Tourmaline'), 'Fragment of Knowledge', 'Int/Wis/Cha'),
    ('Standard Might', 33, 37, ('Topaz', 'Topaz Dust'), 'Essence of Light', 'Strength'),
    ('Standard Blades Aggression', 33, 37, ('Amethyst', 'Gold Shards'), 'Essence of Light', 'Edged WC'),
    ('Standard Blades Protection', 34, 38, ('Gold Shards', 'Topaz'), 'Essence of Light', 'Edged AC'),
    ('Standard Crushing Protection', 35, 39, ('Mithril Shards', 'Topaz'), 'Essence of Water', 'Blunt AC'),
    ('Standard Agility', 35, 39, ('Eye of Air', 'Topaz Dust'), 'Essence of Light', 'Dexterity'),
    ('Standard Crushing Aggression', 36, 40, ('Amethyst', 'Mithril Shards'), 'Essence of Water', 'Blunt WC'),
    ('Standard Health', 37, 41, ("Happy Ed's Tears", 'Hematite Dust'), 'Essence of Shadow', 'HP Regeneration'),
    ('Standard Flame Protection', 37, 41, ('Core of Flame', 'Mithril Shards'), 'Essence of Light', 'Fire AC'),
    ('Standard Flame Aggression', 38, 42, ('Core of Flame', 'Mithril Shards'), 'Essence of Light', 'Fire WC'),
    ('Standard Endurance', 39, 43, ("Happy Ed's Tears", 'Hematite Dust'), 'Essence of Shadow', 'Constitution'),
    ('Standard Acid Protection', 40, 44, ('Amethyst', 'Mithril Shards'), 'Essence of Might', 'Acid AC'),
    ('Standard Acid Aggression', 41, 45, ('Amethyst', 'Mithril Shards'), 'Essence of Might', 'Acid WC'),
    ('Standard Frost Protection', 42, 46, ('Core of Frost', 'Mithril Shards'), 'Essence of Water', 'Ice/Cold AC'),
    ('Standard Lion', 42, 46, ('Heliodor Dust', 'Topaz'), 'Essence of Might', 'Str/Con'),
    ('Standard Spirit', 43, 47, ('Topaz', 'Hematite Dust'), 'Essence of Rejuvenation', 'SP Regeneration'),
    ('Standard Terminator', 43, 47, ('Heliodor', 'Heliodor Dust'), 'Essence of Might', 'Str/Dex'),
    ('Standard Frost Aggression', 43, 47, ('Core of Frost', 'Mithril Shards'), 'Essence of Water', 'Ice/Cold WC'),
    ('Standard Electric Protection', 44, 48, ('Core of Flame', 'Titanium Shards'), 'Essence of Rage', 'Electric AC'),
    ('Standard Smarts', 44, 48, ('Core of Frost', 'Hematite Dust'), 'Essence of Shadow', 'Intelligence'),
    ('Standard Clever Thief', 45, 49, ("Happy Ed's Tears", 'Heliodor Dust'), 'Essence of Shadow', 'Dex/Int'),
    ('Standard Electric Aggression', 45, 49, ('Core of Flame', 'Titanium Shards'), 'Essence of Rage', 'Electric WC'),
    ('Standard Excessive Health', 46, 50, ('Heliodor', 'Hematite Dust'), 'Essence of Rejuvenation', 'Overmax HP Regen'),
    ('Standard Wolf', 47, 51, ('Heliodor', 'Heliodor Dust'), 'Essence of Soul', 'Dex/Con'),
    ('Standard Mental Protection', 47, 51, ('Core of Frost', 'Titanium Shards'), 'Essence of Rage', 'Mental AC'),
    ('Standard Scholar', 47, 51, ('Hematite', 'Hematite Dust'), 'Essence of Soul', 'Int/Wis'),
    ('Standard Mental Aggression', 48, 52, ('Core of Frost', 'Titanium Shards'), 'Essence of Rage', 'Mental WC'),
    ('Standard Insight', 48, 52, ('Hematite', 'Peridot Dust'), 'Essence of Soul', 'Wisdom'),
    ('Standard Suave Thief', 48, 52, ('Heliodor Dust', 'Hematite'), 'Essence of Soul', 'Dex/Cha'),
    ('Standard Energy Protection', 49, 53, ('Peridot', 'Titanium Shards'), 'Essence of Soul', 'Energy AC'),
    ('Standard Energy Aggression', 50, 54, ('Peridot', 'Titanium Shards'), 'Essence of Soul', 'Energy WC'),
    ('Standard Excessive Spirit', 50, 54, ('Peridot', 'Peridot Dust'), 'Essence of Soul', 'Overmax SP Regen'),
    ('Standard Assault Protection', 50, 54, ('Core of Earth', 'Ebon Shards'), 'Essence of The Unseen', 'Edged and Blunt AC'),
    ('Standard Persuasiveness', 50, 54, ('Hematite', 'Peridot Dust'), 'Essence of The Unseen', 'Charisma'),
    ('Standard Barbarian', 51, 55, ('Heliodor', 'Peridot Dust'), 'Essence of The Unseen', 'Int/Str'),
    ('Standard Assault Aggression', 51, 55, ('Core of Earth', 'Ebon Shards'), 'Essence of The Unseen', 'Edged and Blunt WC'),
    ('Standard Elements Protection', 52, 56, ('Core of Flame', 'Core of Frost'), 'Essence of The Unseen', 'Fire and Ice AC'),
    ('Standard Jackal', 52, 56, ('Heliodor Dust', 'Peridot'), 'Essence of Ascension', 'Int/Con'),
    ('Standard health and spirit', 52, 56, ('Heliodor', 'Peridot Dust'), 'Essence of The Unseen', 'HP/SP regen'),
    ('Standard Poison Protection', 53, 57, ('Core of Earth', 'Ebon Shards'), 'Essence of Ascension', 'Poison AC'),
    ('Standard Elements Aggression', 53, 57, ('Core of Flame', 'Core of Frost'), 'Essence of The Unseen', 'Fire and Ice WC'),
    ('Standard Thespian', 53, 57, ('Peridot', 'Peridot Dust'), 'Essence of Ascension', 'Int/Cha'),
    ('Standard Detective', 54, 58, ('Heliodor Dust', 'Peridot'), 'Essence of Blasting', 'Str/Cha'),
    ('Standard Poison Aggression', 54, 58, ('Core of Earth', 'Ebon Shards'), 'Essence of Ascension', 'Poison WC'),
    ('Standard Radiation Protection', 55, 59, ('Adamantium Shards', 'Pearl'), 'Essence of Damnation', 'Radiation AC'),
    ('Standard Thief At Large', 55, 59, ('Pearl', 'Peridot Dust'), 'Essence of Blasting', 'Dex/Wis'),
    ('Standard Devouring Protection', 56, 60, ('Adamantium Shards', 'Core of Earth'), 'Essence of Willy', 'Poison and Acid AC'),
    ('Standard Radiation Aggression', 56, 60, ('Adamantium Shards', 'Pearl'), 'Essence of Damnation', 'Radiation WC'),
    ('Standard Elephant', 57, 61, ('Pearl', 'Pearl Dust'), 'Essence of Willy', 'Con/Wis'),
    ('Standard Spirit And Excessive Health', 57, 61, ('Peridot', 'Pearl Dust'), 'Essence of Damnation', 'Overmax HP Regen & SP Regen'),
    ('Standard Devouring Aggression', 58, 62, ('Adamantium Shards', 'Core of Earth'), 'Essence of Willy', 'Poison and Acid AC'),
    ('Standard Domination Protection', 59, 63, ('Core of Air', 'Obsidian Shards'), 'Essence of Destruction', 'Mental AC'),
    ('Standard Abbot', 59, 63, ('Core of Air', 'Peridot Dust'), 'Essence of Destruction', 'Wis/Cha'),
    ('Standard Agent', 60, 64, ('Opal', 'Opal Dust'), 'Essence of Compassion', 'Str/Wis'),
    ('Standard Athlete', 60, 64, ('Opal', 'Pearl Dust'), 'Essence of Knowledge', 'Str/Dex/Con'),
    ('Standard Health And Excessive Spirit', 60, 64, ('Opal', 'Pearl Dust'), 'Essence of Destruction', 'HP Regen & Overmax SP Regen'),
    ('Standard Irradiation Aggression', 61, 65, ('Core of Air', 'Obsidian Shards'), 'Essence of Compassion', 'Electric and Radiation WC'),
    ('Standard Domination Aggression', 61, 65, ('Core of Air', 'Adamantium Shards'), 'Essence of Destruction', 'Mental and Energy WC'),
    ('Standard Irradiation Protection', 62, 66, ('Core of Air', 'Obsidian Shards'), 'Essence of Compassion', 'Electric and Radiation AC'),
    ('Standard Koala', 63, 67, ('Opal', 'Opal Dust'), 'Essence of Knowledge', 'Con/Cha'),
    ('Standard Despot', 64, 68, ("Ghoti's Tears", 'Pearl Dust'), 'Essence of Knowledge', 'Int/Wis/Cha'),
    ('Standard Excessive Health And Spirit', 65, 69, ('Pearl', 'Opal Dust'), 'Essence of Knowledge', 'Overmax HP/SP Regen'),
    ('Major Blades Aggression', 66, 70, ("Ghoti's Tears", 'Obsidian Shards'), 'Heart of Light', ''),
    ('Major Might', 66, 70, ('Opal', 'Opal Dust'), 'Heart of Light', 'Strength'),
    ('Major Blades Protection', 67, 71, ("Ghoti's Tears", 'Obsidian Shards'), 'Heart of Light', ''),
    ('Major Crushing Protection', 68, 72, ("Ghoti's Tears", 'Nethernium Shards'), 'Heart of Water', ''),
    ('Major Agility', 68, 72, ('Star of Flame', 'Opal Dust'), 'Heart of Light', 'Dexterity'),
    ('Major Crushing Aggression', 69, 73, ("Ghoti's Tears", 'Nethernium Shards'), 'Heart of Water', ''),
    ('Major Health', 70, 74, ('Star of Flame', 'Opal Dust'), 'Heart of Shadow', ''),
    ('Major Flame Protection', 70, 74, ('Star of Flame', 'Nethernium Shards'), 'Heart of Light', ''),
    ('Major Flame Aggression', 71, 75, ('Star of Flame', 'Nethernium Shards'), 'Heart of Light', ''),
    ('Major Endurance', 72, 76, ('Star of Flame', 'Opal Dust'), 'Heart of Shadow', 'Constitution'),
    ('Major Frost Protection', 73, 77, ('Star of Frost', 'Voidstone Shards'), 'Heart of Water', ''),
    ('Major Frost Aggression', 74, 78, ('Star of Frost', 'Voidstone Shards'), 'Heart of Water', ''),
    ('Major Acid Protection', 75, 79, ("Shansabyk's Tears", 'Voidstone Shards'), 'Heart of Might', ''),
    ('Major Lion', 75, 79, ('Diamond Dust', 'Diamond'), 'Heart of Might', 'Constitution/Strength'),
    ('Major Acid Aggression', 76, 80, ("Shansabyk's Tears", 'Voidstone Shards'), 'Heart of Might', ''),
    ('Major Spirit', 76, 80, ('Diamond', 'Opal Dust'), 'Heart of Rejuvenation', 'SP Regeneration'),
    ('Major Terminator', 76, 80, ('Diamond Dust', 'Star of Frost'), 'Heart of Might', 'Strength/Dexterity'),
    ('Major Smarts', 77, 81, ('Diamond Dust', 'Diamond'), 'Heart of Shadow', 'Intelligence'),
    ('Major Electric Protection', 77, 81, ("Shansabyk's Tears", 'Voidstone Shards'), 'Heart of Rage', ''),
    ('Major Clever Thief', 78, 82, ('Diamond Dust', 'Star of Flame'), 'Heart of Shadow', 'Dexterity/Intelligence'),
    ('Major Electric Aggression', 78, 82, ("Shansabyk's Tears", 'Voidstone Shards'), 'Heart of Rage', ''),
    ('Major Excessive Health', 79, 83, ('Diamond', 'Opal Dust'), 'Heart of Rejuvenation', 'Overmax HP Regen'),
    ('Major Mental Protection', 80, 84, ('Phasemetal Shards', 'Emerald'), 'Heart of Rage', ''),
    ('Major Scholar', 80, 84, ('Diamond', 'Diamond Dust'), 'Heart of Soul', 'Intelligence/Wisdom'),
    ('Major Wolf', 80, 84, ('Emerald', 'Emerald Dust'), 'Heart of Soul', 'Dexterity/Constitution'),
    ('Major Mental Aggression', 81, 85, ('Phasemetal Shards', 'Emerald'), 'Heart of Rage', ''),
    ('Major Suave Thief', 81, 85, ('Diamond Dust', 'Star of Frost'), 'Heart of Soul', 'Dexterity/Charisma'),
    ('Major Insight', 81, 85, ('Emerald', 'Emerald Dust'), 'Heart of Soul', 'Wisdom'),
    ('Major Energy Protection', 82, 86, ('Phasemetal Shards', 'Star of Air'), 'Heart of Soul', ''),
    ('Major Excessive Spirit', 83, 87, ('Emerald Dust', "Shansabyk's Tears"), 'Heart of Soul', ''),
    ('Major Persuasiveness', 83, 87, ('Emerald Dust', 'Star of Frost'), 'Heart of The Unseen', 'Charisma'),
    ('Major Energy Aggression', 83, 87, ('Phasemetal Shards', 'Star of Air'), 'Heart of Soul', ''),
    ('Major Assault Protection', 83, 87, ('Phasemetal Shards', 'Star of Air'), 'Heart of The Unseen', ''),
    ('Major Barbarian', 84, 88, ('Emerald', 'Emerald Dust'), 'Heart of The Unseen', 'Intelligence/Strength'),
    ('Major Assault Aggression', 84, 88, ('Phasemetal Shards', 'Star of Air'), 'Heart of The Unseen', ''),
    ('Major Jackal', 85, 89, ('Sapphire', 'Sapphire Dust'), 'Heart of Ascension', 'Intelligence/Constitution'),
    ('Major Elements Protection', 85, 89, ('Star of Flame', 'Star of Frost'), 'Heart of The Unseen', ''),
    ('Major Thespian', 86, 90, ('Emerald Dust', 'Sapphire'), 'Heart of Ascension', 'Intelligence/Charisma'),
    ('Major Elements Aggression', 86, 90, ('Star of Flame', 'Star of Frost'), 'Heart of The Unseen', ''),
    ('Major Poison Protection', 86, 90, ('Phasemetal Shards', 'Star of Air'), 'Heart of Ascension', ''),
    ('Major Poison Aggression', 87, 91, ('Phasemetal Shards', 'Star of Air'), 'Heart of Ascension', ''),
    ('Major Detective', 87, 91, ('Sapphire', 'Sapphire Dust'), 'Heart of Blasting', 'Strength/Charisma'),
    ('Major Radiation Protection', 88, 92, ('Phasemetal Shards', 'Sapphire'), 'Heart of Damnation', ''),
    ('Major Thief At Large', 88, 92, ('Emerald', 'Sapphire Dust'), 'Heart of Blasting', 'Dexterity/Wisdom'),
    ('Major Radiation Aggression', 89, 93, ('Phasemetal Shards', 'Sapphire'), 'Heart of Damnation', ''),
    ('Major Devouring Protection', 89, 93, ('Phasemetal Shards', 'Star of Earth'), 'Heart of Willy', ''),
    ('Major Elephant', 90, 94, ('Ruby Dust', 'Star of Earth'), 'Heart of Willy', 'Constitution/Wisdom'),
    ('Major spirit and excessive health', 90, 94, ('Star of Earth', 'Sapphire Dust'), 'Heart of Damnation', 'SP Regen and Overmax HP Regen'),
    ('Major Devouring Aggression', 91, 95, ('Phasemetal Shards', 'Star of Earth'), 'Heart of Willy', ''),
    ('Major Domination Protection', 92, 96, ("Cancer's Tears", 'Chaostone Shards'), 'Heart of Destruction', ''),
    ('Major Abbot', 92, 96, ('Ruby', 'Ruby Dust'), 'Heart of Destruction', 'Wisdom/Charisma'),
    ('Major Athlete', 93, 97, ('Ruby', 'Ruby Dust'), 'Heart of Knowledge', 'Strength/Dexterity/Constitution'),
    ('Major Agent', 93, 97, ('Sapphire', 'Sapphire Dust'), 'Heart of Compassion', 'Strength/Wisdom'),
    ('Major Domination Aggression', 94, 98, ("Cancer's Tears", 'Chaostone Shards'), 'Heart of Destruction', ''),
    ('Major Irradiation Aggression', 94, 98, ('Chaostone Shards', 'Ruby'), 'Heart of Compassion', ''),
    ('Major Irradiation Protection', 95, 99, ('Chaostone Shards', 'Ruby'), 'Heart of Compassion', ''),
    ('Major Koala', 96, 100, ("Cancer's Tears", 'Sapphire Dust'), 'Heart of Knowledge', 'Constitution/Charisma'),
    ('Major Despot', 97, 101, ('Ruby', 'Ruby Dust'), 'Heart of Knowledge', 'Intelligence/Wisdom/Charisma'),
    ('Major Excessive Health and Spirit', 98, 101, ("Cancer's Tears", 'Ruby Dust'), 'Heart of Knowledge', ''),
)

#: (jewel, first level, trivial at, what it transmutes into)
JEWELS = (
    ('aquamarine', 1, 10, ('tigers eye dust', 'morganite dust', 'copper shards', 'aquamarine dust', 'tigers eye', 'morganite')),
    ('aquamarine dust', 1, 10, ('tigers eye dust', 'aquamarine', 'morganite dust', 'copper shards', 'tigers eye', 'morganite')),
    ('copper shards', 1, 10, ('tigers eye dust', 'aquamarine', 'morganite dust', 'aquamarine dust', 'tigers eye', 'morganite')),
    ('morganite', 1, 10, ('tigers eye dust', 'aquamarine', 'morganite dust', 'copper shards', 'aquamarine dust', 'tigers eye')),
    ('morganite dust', 1, 10, ('tigers eye dust', 'aquamarine', 'copper shards', 'aquamarine dust', 'tigers eye', 'morganite')),
    ("tiger's eye", 1, 10, ('tigers eye dust', 'aquamarine', 'morganite dust', 'copper shards', 'aquamarine dust', 'morganite')),
    ("tiger's eye dust", 1, 10, ('aquamarine', 'morganite dust', 'copper shards', 'aquamarine dust', 'tigers eye', 'morganite')),
    ('fragment of light', 2, 12, ('knowledge', 'rejuvenation', 'damnation', 'shadow', 'rage', 'compassion', 'blasting', 'soul', 'water', 'destruction', 'might', 'ascension', 'the unseen', 'willy')),
    ('fragment of water', 5, 15, ('knowledge', 'rejuvenation', 'damnation', 'shadow', 'rage', 'compassion', 'blasting', 'soul', 'destruction', 'might', 'ascension', 'the unseen', 'willy', 'light')),
    ('fragment of shadow', 6, 16, ('knowledge', 'rejuvenation', 'damnation', 'rage', 'compassion', 'blasting', 'water', 'soul', 'destruction', 'might', 'ascension', 'the unseen', 'willy', 'light')),
    ('bronze shards', 7, 15, ('cats eye dust', 'cats eye', 'garnet dust', 'eye of flame', 'garnet')),
    ("cat's eye", 7, 15, ('cats eye dust', 'eye of flame', 'garnet dust', 'garnet', 'bronze shards')),
    ("cat's eye dust", 7, 15, ('cats eye', 'garnet dust', 'eye of flame', 'garnet', 'bronze shards')),
    ('eye of flame', 7, 15, ('cats eye dust', 'cats eye', 'garnet dust', 'garnet', 'bronze shards')),
    ('garnet', 7, 15, ('cats eye dust', 'cats eye', 'garnet dust', 'eye of flame', 'bronze shards')),
    ('garnet dust', 7, 15, ('cats eye dust', 'cats eye', 'eye of flame', 'garnet', 'bronze shards')),
    ('fragment of might', 9, 19, ('knowledge', 'rejuvenation', 'damnation', 'shadow', 'rage', 'compassion', 'blasting', 'water', 'soul', 'destruction', 'ascension', 'the unseen', 'willy', 'light')),
    ('alexandrite', 10, 20, ('garnet dust', 'alexandrite dust', 'iron shards', 'eye of frost', 'garnet')),
    ('alexandrite dust', 10, 20, ('alexandrite', 'iron shards', 'garnet dust', 'garnet', 'eye of frost')),
    ('eye of frost', 10, 20, ('alexandrite', 'alexandrite dust', 'iron shards', 'garnet dust', 'garnet')),
    ('iron shards', 10, 20, ('alexandrite', 'alexandrite dust', 'garnet dust', 'eye of frost', 'garnet')),
    ('fragment of rejuvenation', 12, 22, ('knowledge', 'damnation', 'shadow', 'compassion', 'rage', 'blasting', 'soul', 'water', 'destruction', 'might', 'ascension', 'the unseen', 'willy', 'light', 'rejuvenation')),
    ('fragment of rage', 13, 23, ('knowledge', 'rejuvenation', 'damnation', 'shadow', 'compassion', 'blasting', 'soul', 'water', 'destruction', 'might', 'ascension', 'the unseen', 'willy', 'light')),
    ('fragment of soul', 15, 25, ('knowledge', 'rejuvenation', 'damnation', 'shadow', 'rage', 'compassion', 'blasting', 'water', 'destruction', 'might', 'ascension', 'the unseen', 'willy', 'light')),
    ('steel shards', 15, 25, ('eye of flame', 'cats eye dust', 'cats eye', 'eye of frost')),
    ('fragment of the unseen', 18, 28, ('knowledge', 'rejuvenation', 'damnation', 'shadow', 'rage', 'compassion', 'blasting', 'water', 'soul', 'destruction', 'might', 'ascension', 'willy', 'light')),
    ('beryl', 20, 30, ('beryl dust', 'tourmaline dust', 'roans tears', 'eye of earth', 'pyrite', 'tourmaline', 'silver shards', 'pyrite dust')),
    ('beryl dust', 20, 30, ('beryl', 'tourmaline dust', 'roans tears', 'pyrite', 'eye of earth', 'tourmaline', 'silver shards', 'pyrite dust')),
    ('eye of earth', 20, 30, ('beryl', 'beryl dust', 'tourmaline dust', 'roans tears', 'pyrite', 'tourmaline', 'silver shards', 'pyrite dust')),
    ('pyrite', 20, 30, ('beryl', 'beryl dust', 'tourmaline dust', 'roans tears', 'eye of earth', 'tourmaline', 'silver shards', 'pyrite dust')),
    ('pyrite dust', 20, 30, ('beryl', 'beryl dust', 'tourmaline dust', 'roans tears', 'pyrite', 'eye of earth', 'tourmaline', 'silver shards')),
    ("roan's tears", 20, 30, ('beryl', 'beryl dust', 'tourmaline dust', 'eye of earth', 'pyrite', 'tourmaline', 'silver shards', 'pyrite dust')),
    ('silver shards', 20, 30, ('beryl', 'beryl dust', 'tourmaline dust', 'roans tears', 'pyrite', 'eye of earth', 'tourmaline', 'pyrite dust')),
    ('tourmaline', 20, 30, ('beryl', 'beryl dust', 'tourmaline dust', 'roans tears', 'eye of earth', 'pyrite', 'silver shards', 'pyrite dust')),
    ('tourmaline dust', 20, 30, ('beryl', 'beryl dust', 'roans tears', 'eye of earth', 'pyrite', 'tourmaline', 'silver shards', 'pyrite dust')),
    ('fragment of ascension', 21, 31, ('knowledge', 'rejuvenation', 'damnation', 'shadow', 'rage', 'compassion', 'blasting', 'water', 'soul', 'destruction', 'might', 'the unseen', 'willy', 'light')),
    ('fragment of blasting', 23, 33, ('knowledge', 'rejuvenation', 'damnation', 'shadow', 'rage', 'compassion', 'soul', 'water', 'destruction', 'might', 'ascension', 'the unseen', 'willy', 'light')),
    ('fragment of damnation', 24, 34, ('knowledge', 'rejuvenation', 'shadow', 'compassion', 'rage', 'blasting', 'soul', 'water', 'destruction', 'might', 'ascension', 'the unseen', 'willy', 'light')),
    ('amethyst', 25, 35, ('happy eds tears', 'eye of air', 'amethyst dust', 'gold shards', 'topaz dust', 'topaz')),
    ('amethyst dust', 25, 35, ('happy eds tears', 'eye of air', 'gold shards', 'amethyst', 'topaz dust', 'topaz')),
    ('eye of air', 25, 35, ('happy eds tears', 'amethyst dust', 'gold shards', 'amethyst', 'topaz dust', 'topaz')),
    ('gold shards', 25, 35, ('happy eds tears', 'eye of air', 'amethyst dust', 'amethyst', 'topaz dust', 'topaz')),
    ("happy ed's tears", 25, 35, ('eye of air', 'amethyst dust', 'gold shards', 'amethyst', 'topaz dust', 'topaz')),
    ('topaz', 25, 35, ('happy eds tears', 'eye of air', 'gold shards', 'amethyst', 'topaz dust')),
    ('topaz dust', 25, 35, ('happy eds tears', 'amethyst dust', 'eye of air', 'gold shards', 'amethyst', 'topaz')),
    ('fragment of willy', 27, 37, ('knowledge', 'damnation', 'rejuvenation', 'shadow', 'compassion', 'rage', 'blasting', 'soul', 'water', 'destruction', 'might', 'ascension', 'the unseen', 'light')),
    ('fragment of destruction', 28, 38, ('knowledge', 'rejuvenation', 'damnation', 'shadow', 'rage', 'compassion', 'blasting', 'water', 'soul', 'might', 'ascension', 'the unseen', 'willy', 'light')),
    ('fragment of compassion', 30, 40, ('knowledge', 'rejuvenation', 'damnation', 'shadow', 'rage', 'blasting', 'soul', 'water', 'destruction', 'might', 'ascension', 'the unseen', 'willy', 'light')),
    ('fragment of knowledge', 32, 42, ('rejuvenation', 'damnation', 'shadow', 'rage', 'compassion', 'blasting', 'water', 'soul', 'destruction', 'might', 'ascension', 'the unseen', 'willy', 'light')),
    ('core of flame', 33, 43, ('mithril shards', 'heliodor', 'heliodor dust', 'hematite dust', 'hematite')),
    ('essence of light', 33, 43, ('knowledge', 'compassion', 'damnation', 'blasting', 'water', 'destruction', 'might', 'shadow', 'soul', 'ascension', 'willy', 'the unseen', 'rage', 'rejuvenation')),
    ('heliodor', 33, 43, ('mithril shards', 'heliodor dust', 'hematite dust', 'hematite', 'core of flame')),
    ('heliodor dust', 33, 43, ('mithril shards', 'heliodor', 'hematite dust', 'hematite', 'core of flame')),
    ('hematite', 33, 43, ('mithril shards', 'heliodor', 'heliodor dust', 'hematite dust', 'core of flame')),
    ('hematite dust', 33, 43, ('mithril shards', 'heliodor', 'heliodor dust', 'hematite', 'core of flame')),
    ('mithril shards', 33, 43, ('heliodor', 'heliodor dust', 'core of flame', 'hematite dust', 'hematite')),
    ('essence of water', 36, 46, ('knowledge', 'compassion', 'damnation', 'blasting', 'destruction', 'might', 'shadow', 'soul', 'ascension', 'willy', 'the unseen', 'rage', 'rejuvenation', 'light')),
    ('essence of shadow', 37, 47, ('knowledge', 'compassion', 'damnation', 'water', 'blasting', 'destruction', 'might', 'soul', 'ascension', 'willy', 'the unseen', 'rage', 'rejuvenation', 'light')),
    ('essence of might', 40, 50, ('knowledge', 'compassion', 'damnation', 'water', 'blasting', 'destruction', 'shadow', 'soul', 'ascension', 'willy', 'the unseen', 'rage', 'rejuvenation', 'light')),
    ('core of frost', 42, 52, ('peridot', 'titanium shards', 'peridot dust')),
    ('peridot', 42, 52, ('titanium shards', 'peridot dust', 'core of frost')),
    ('peridot dust', 42, 52, ('titanium shards', 'peridot', 'core of frost')),
    ('titanium shards', 42, 52, ('peridot dust', 'peridot', 'core of frost')),
    ('essence of rejuvenation', 43, 53, ('knowledge', 'compassion', 'damnation', 'blasting', 'water', 'destruction', 'might', 'shadow', 'soul', 'ascension', 'willy', 'the unseen', 'rage', 'light')),
    ('essence of rage', 44, 54, ('knowledge', 'compassion', 'damnation', 'blasting', 'water', 'destruction', 'might', 'shadow', 'soul', 'ascension', 'willy', 'the unseen', 'rejuvenation', 'light')),
    ('essence of soul', 46, 56, ('knowledge', 'compassion', 'damnation', 'blasting', 'water', 'destruction', 'might', 'shadow', 'ascension', 'willy', 'the unseen', 'rage', 'rejuvenation', 'light')),
    ('adamantium shards', 55, 65, ('core of air', 'pearl dust', 'pearl')),
    ('core of air', 55, 65, ('pearl dust', 'adamantium shards', 'pearl')),
    ('essence of damnation', 55, 65, ('knowledge', 'compassion', 'blasting', 'water', 'destruction', 'might', 'shadow', 'soul', 'ascension', 'willy', 'the unseen', 'rage', 'rejuvenation', 'light')),
    ('pearl', 55, 65, ('core of air', 'pearl dust', 'adamantium shards')),
    ('pearl dust', 55, 65, ('core of air', 'pearl', 'adamantium shards')),
    ('essence of willy', 58, 68, ('knowledge', 'compassion', 'damnation', 'blasting', 'water', 'destruction', 'might', 'shadow', 'soul', 'ascension', 'the unseen', 'rage', 'rejuvenation', 'light')),
    ('essence of destruction', 59, 69, ('knowledge', 'compassion', 'damnation', 'water', 'blasting', 'might', 'shadow', 'soul', 'ascension', 'willy', 'the unseen', 'rage', 'rejuvenation', 'light')),
    ("ghoti's tears", 60, 70, ('opal dust', 'pearl dust', 'opal', 'pearl', 'obsidian shards')),
    ('obsidian shards', 60, 70, ("ghoti's tears", 'pearl dust', 'opal dust', 'opal', 'pearl')),
    ('opal', 60, 70, ("ghoti's tears", 'opal dust', 'pearl dust', 'obsidian shards', 'pearl')),
    ('opal dust', 60, 70, ("ghoti's tears", 'pearl dust', 'opal', 'obsidian shards', 'pearl')),
    ('essence of compassion', 61, 71, ('knowledge', 'damnation', 'blasting', 'water', 'destruction', 'might', 'shadow', 'soul', 'ascension', 'willy', 'the unseen', 'rage', 'rejuvenation', 'light')),
    ('essence of knowledge', 63, 73, ('compassion', 'damnation', 'water', 'blasting', 'destruction', 'might', 'shadow', 'soul', 'ascension', 'willy', 'the unseen', 'rage', 'rejuvenation', 'light')),
    ('star of flame', 65, 75, ('opal dust', 'opal', 'nethernium shards', "ghoti's tears")),
    ('nethernium shards', 65, 75, ('star of flame', 'opal dust', 'opal', "ghoti's tears")),
    ('heart of light', 66, 76, ('willy', 'damnation', 'blasting', 'water', 'rejuvenation', 'might', 'destruction', 'shadow', 'ascension', 'the unseen', 'knowledge', 'rage', 'compassion', 'soul')),
    ('heart of water', 69, 79, ('willy', 'damnation', 'blasting', 'rejuvenation', 'might', 'destruction', 'shadow', 'ascension', 'the unseen', 'knowledge', 'rage', 'compassion', 'light', 'soul')),
    ('heart of shadow', 70, 80, ('water', 'willy', 'damnation', 'blasting', 'rejuvenation', 'might', 'destruction', 'ascension', 'the unseen', 'knowledge', 'rage', 'compassion', 'light', 'soul')),
    ('heart of might', 73, 83, ('water', 'willy', 'damnation', 'blasting', 'rejuvenation', 'destruction', 'shadow', 'ascension', 'the unseen', 'knowledge', 'rage', 'compassion', 'light', 'soul')),
    ('diamond', 73, 83, ('star of frost', 'diamond dust', 'voidstone shards', 'shansabyks tears')),
    ('diamond dust', 73, 83, ('star of frost', 'voidstone shards', 'shansabyks tears', 'diamond')),
    ('star of frost', 73, 83, ('diamond dust', 'voidstone shards', 'shansabyks tears', 'diamond')),
    ('shansabyks tears', 73, 83, ('star of frost', 'diamond dust', 'voidstone shards', 'diamond')),
    ('voidstone shards', 73, 83, ('star of frost', 'diamond dust', 'shansabyks tears', 'diamond')),
    ('heart of rejuvenation', 76, 86, ('willy', 'damnation', 'blasting', 'water', 'might', 'destruction', 'shadow', 'ascension', 'the unseen', 'knowledge', 'compassion', 'rage', 'light', 'soul')),
    ('heart of rage', 77, 87, ('willy', 'damnation', 'blasting', 'water', 'rejuvenation', 'might', 'destruction', 'shadow', 'ascension', 'the unseen', 'knowledge', 'compassion', 'light', 'soul')),
    ('heart of soul', 79, 89, ('willy', 'damnation', 'blasting', 'water', 'rejuvenation', 'might', 'destruction', 'shadow', 'ascension', 'the unseen', 'knowledge', 'rage', 'compassion', 'light')),
    ('emerald', 80, 90, ('sapphire dust', 'star of air', 'emerald dust', 'phasemetal shards', 'sapphire', 'star of earth')),
    ('emerald dust', 80, 90, ('sapphire dust', 'star of air', 'phasemetal shards', 'sapphire', 'emerald', 'star of earth')),
    ('star of air', 80, 90, ('sapphire dust', 'emerald', 'emerald dust', 'phasemetal shards', 'sapphire', 'star of earth')),
    ('star of earth', 80, 90, ('sapphire dust', 'star of air', 'emerald', 'emerald dust', 'phasemetal shards', 'sapphire')),
    ('sapphire dust', 80, 90, ('star of air', 'star of earth', 'sapphire', 'emerald', 'emerald dust', 'phasemetal shards')),
    ('phasemetal shards', 80, 90, ('star of earth', 'sapphire', 'star of air', 'sapphire dust', 'emerald dust', 'emerald')),
    ('heart of the unseen', 82, 92, ('water', 'willy', 'damnation', 'blasting', 'rejuvenation', 'might', 'destruction', 'shadow', 'ascension', 'knowledge', 'rage', 'compassion', 'light', 'soul')),
    ('heart of ascension', 85, 95, ('water', 'willy', 'damnation', 'blasting', 'rejuvenation', 'might', 'destruction', 'shadow', 'the unseen', 'knowledge', 'rage', 'compassion', 'light', 'soul')),
    ('heart of blasting', 87, 97, ('willy', 'damnation', 'water', 'rejuvenation', 'might', 'destruction', 'shadow', 'ascension', 'the unseen', 'knowledge', 'rage', 'compassion', 'light')),
    ('heart of damnation', 88, 98, ('willy', 'blasting', 'water', 'rejuvenation', 'might', 'destruction', 'shadow', 'ascension', 'the unseen', 'knowledge', 'compassion', 'rage', 'light')),
    ('sapphire', 90, 100, ('sapphire dust', 'emerald', 'chaostone shards', 'cancers tears', 'ruby', 'ruby dust', 'emerald dust')),
    ('chaostone shards', 90, 100, ('sapphire', 'sapphire dust', 'emerald', 'cancers tears', 'ruby', 'ruby dust', 'emerald dust')),
    ('ruby', 90, 100, ('sapphire', 'sapphire dust', 'emerald', 'chaostone shards', 'cancers tears', 'ruby dust', 'emerald dust')),
    ('ruby dust', 90, 100, ('sapphire', 'sapphire dust', 'emerald', 'chaostone shards', 'cancers tears', 'ruby', 'emerald dust')),
    ('heart of willy', 91, 101, ('damnation', 'blasting', 'water', 'rejuvenation', 'might', 'destruction', 'shadow', 'ascension', 'the unseen', 'knowledge', 'compassion', 'rage', 'light', 'soul')),
    ('heart of destruction', 92, 102, ('water', 'willy', 'damnation', 'blasting', 'rejuvenation', 'might', 'shadow', 'ascension', 'the unseen', 'knowledge', 'rage', 'compassion', 'light', 'soul')),
    ('heart of compassion', 94, 104, ('willy', 'damnation', 'blasting', 'water', 'rejuvenation', 'might', 'destruction', 'shadow', 'ascension', 'the unseen', 'knowledge', 'rage', 'light')),
    ('heart of knowledge', 96, 106, ('water', 'willy', 'damnation', 'blasting', 'rejuvenation', 'might', 'destruction', 'shadow', 'ascension', 'the unseen', 'rage', 'compassion', 'light', 'soul')),
)
